/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '3/19/25, 12:38 AM' 
 * Generated by 'u64128027' 
 * Generated on server 'ODAWS02-USW2.ODA.SAS.COM' 
 * Generated on SAS platform 'Linux LIN X64 5.14.0-284.30.1.el9_2.x86_64' 
 * Generated on SAS version '9.04.01M7P08062020' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36' 
 * Generated on web client 'https://odamid-usw2.oda.sas.com/SASStudio/main?locale=en_US&zone=GMT-05%253A00&ticket=ST-186191-eysyfUQQryqEWBjfI4tz-cas' 
 *
 */

ods graphics / reset width=6.4in height=4.8in imagemap;

proc sgplot data=SASHELP.CARS (where=(type ne "Hybrid"));
	title height=14pt "Distribution of Mileage";
	histogram MPG_City / showbins nbins=20;
	density MPG_City;
	density MPG_City / type=Kernel;
	yaxis grid;
run;

ods graphics / reset;
title;